serviceAccount:
  create: true # Disable service account creation
  name: "" # Your existing GCP service account
hpa:
  name: app1-hpa
  minReplicas: 1
  maxReplicas: 5
  metrics:
    resource: cpu
    targetType: Utilization
    averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        value: 1
        periodSeconds: 60
replicaCount: 1
image:
  repository: us-central1-docker.pkg.dev/hello-project-439605-s1/new-apps-repo/app1
  tag: '8ecc12e2cd55605e8e748125971846c2a16e3ddb'
  pullPolicy: Always
containerPort: 3001
metadata:
  name: app1-deployment
  namespace: default
  labels:
    app: app1
service:
  name: app1-service
  port: 80
  type: ClusterIP
ingress:
  enabled: true
